server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/jobtracker
spring.datasource.username=aarthireddy
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.application.name=jobtracker
groq.api.key=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